select * from customer;


-- Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as total_revenue
from customer
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount from customer
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,review_rating from customer
where review_rating > (select avg(review_rating) from customer)
order by review_rating desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,avg(purchase_amount) as avg_purchase_amount
from customer
where shipping_type in ('Express','Standard')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
select subscription_status, round(avg(purchase_amount),2),sum(purchase_amount) as total_revenue,count(customer_id) as total_customer
from customer
group by  subscription_status
order by total_revenue,total_customer desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
sum(case when discount_applied = 'Yes' then 1 else 0 end) * 100 /count(*) as percent_disc
from customer
group by item_purchased
order by percent_disc desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
select count(*),
case when previous_purchases = 1 then 'New'
           when previous_purchases > 1 and previous_purchases < 11 then 'Returning' else 'loyal' end as segment
from customer
group by segment;

-- Q8. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- Q9. What is the revenue contribution of each age group? 
select age_group,sum(purchase_amount) as revenue_contribution
from customer
group by age_group
order by revenue_contribution desc


	  